all: sieve64-static sieve64-dynamic sieve32-static

sieve64-static: sieve.c dockcross-x64
	./dockcross-x64 bash -c '$$CC sieve.c -o sieve64-static -static'

sieve64-dynamic: sieve.c dockcross-x64
	./dockcross-x64 bash -c '$$CC sieve.c -o sieve64-dynamic'

sieve32-static: sieve.c dockcross-x86
	./dockcross-x86 bash -c '$$CC sieve.c -o sieve32-static -static'

dockcross-x64:
	docker run --rm dockcross/linux-x64 > ./dockcross-x64
	chmod +x ./dockcross-x64

dockcross-x86:
	docker run --rm dockcross/linux-x86 > ./dockcross-x86
	chmod +x ./dockcross-x86

clean:
	rm -f dockcross-* sieve64-static sieve64-dynamic sieve32-static
